"""Public async API for the local Satellite1 daemon."""

from .client import (
    DEFAULT_SOCKET_PATH,
    AsyncSatellite1Client,
    Satellite1ClientError,
    Satellite1ConnectionError,
    Satellite1DaemonError,
    Satellite1ProtocolError,
)
from .models import (
    AudioChangeSource,
    ButtonPressed,
    DaemonInfo,
    EnvironmentReadings,
    HardwareHealth,
    LineOutJackChanged,
    LvaConnectionChanged,
    LvaMicSoftwareMuteChanged,
    LvaTimerChanged,
    MicMuteChanged,
    OutputMuteChanged,
    PowerContract,
    Satellite1Event,
    SpeakerMuteChanged,
    VoicePipelineState,
    VoicePipelineStateChanged,
    VolumeChanged,
    XmosAvailabilityChanged,
    XmosStatus,
)

__all__ = [
    "DEFAULT_SOCKET_PATH",
    "AsyncSatellite1Client",
    "AudioChangeSource",
    "ButtonPressed",
    "DaemonInfo",
    "EnvironmentReadings",
    "HardwareHealth",
    "LvaMicSoftwareMuteChanged",
    "LvaConnectionChanged",
    "LvaTimerChanged",
    "MicMuteChanged",
    "OutputMuteChanged",
    "SpeakerMuteChanged",
    "LineOutJackChanged",
    "PowerContract",
    "Satellite1ClientError",
    "Satellite1ConnectionError",
    "Satellite1DaemonError",
    "Satellite1Event",
    "VolumeChanged",
    "VoicePipelineStateChanged",
    "VoicePipelineState",
    "Satellite1ProtocolError",
    "XmosStatus",
    "XmosAvailabilityChanged",
]
